#!/usr/bin/env node
// Build-time glyph work for the certificate, so the visitor's browser never loads a script face
// and never has to measure text before it draws:
//
//   src/js/certificate/signatures.js  the two signatures as SVG path data, converted from OFL script
//                                     faces kept in scripts/signature-faces/ with their licences:
//                                     Clive Standish in WindSong-Regular.ttf, Diane in
//                                     Petemoss-Regular.ttf. Shaped with HarfBuzz (kerning and
//                                     joins), outlines taken with fontTools.
//   src/js/certificate/metrics.js     advance widths (thousandths of an em) of the certificate faces
//                                     in src/fonts/, for centring, the heading's explicit glyph
//                                     positions, the seal's ring of letters and fitting long names.
//
// Run by hand when a face or a signature changes: `node scripts/certificate-glyphs.mjs`. It runs
// fontTools 4.61.1 and uharfbuzz 0.51.1 through `uv run`, the same way scripts/fonts.py is run.
// The script faces are never copied into src/ or site/. (Jules, 2026-10-04)
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

export const SIGNERS = [
  { id: 'clive', text: 'Clive Standish', face: 'scripts/signature-faces/WindSong-Regular.ttf' },
  { id: 'diane', text: 'Diane', face: 'scripts/signature-faces/Petemoss-Regular.ttf' },
];

// The faces the certificate draws text in, and the weight it uses each at.
export const FACES = [
  { key: 'Cormorant Garamond/500', path: 'src/fonts/CormorantGaramond-Medium.ttf' },
  { key: 'Cormorant Garamond/600', path: 'src/fonts/CormorantGaramond-SemiBold.ttf' },
  { key: 'Inter Tight/700', path: 'src/fonts/InterTight-Bold.ttf' },
  { key: 'JetBrains Mono/500', path: 'src/fonts/JetBrainsMono-Medium.ttf' },
];

const PY = String.raw`
import json, sys
import uharfbuzz as hb
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen

cfg = json.loads(sys.stdin.read())
out = {"signatures": {}, "advances": {}}

SIZE = 100.0  # path units: the signature at a font size of 100, baseline at y = 0

for s in cfg["signers"]:
    path = s["face"]
    data = open(path, "rb").read()
    font = hb.Font(hb.Face(data))
    buf = hb.Buffer()
    buf.add_str(s["text"])
    buf.guess_segment_properties()
    hb.shape(font, buf, {"kern": True, "liga": True, "calt": True})
    tt = TTFont(path)
    gs = tt.getGlyphSet()
    order = tt.getGlyphOrder()
    upm = tt["head"].unitsPerEm
    k = SIZE / upm
    svg = SVGPathPen(gs, ntos=lambda v: ("%.1f" % v).rstrip("0").rstrip("."))
    bounds = BoundsPen(gs)
    x = 0
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        name = order[info.codepoint]
        ox = (x + pos.x_offset) * k
        oy = pos.y_offset * k
        t = (k, 0, 0, -k, ox, -oy)
        gs[name].draw(TransformPen(svg, t))
        gs[name].draw(TransformPen(bounds, t))
        x += pos.x_advance
    xmin, ymin, xmax, ymax = bounds.bounds
    out["signatures"][s["id"]] = {
        "text": s["text"],
        "d": svg.getCommands(),
        "box": [round(xmin, 1), round(ymin, 1), round(xmax, 1), round(ymax, 1)],
        "face": path.split("/")[-1],
    }

ranges = [(0x20, 0x7E), (0xA0, 0x24F), (0x2010, 0x2027), (0x2030, 0x203A), (0x2122, 0x2122)]
for f in cfg["faces"]:
    tt = TTFont(f["path"])
    cmap = tt.getBestCmap()
    hmtx = tt["hmtx"]
    upm = tt["head"].unitsPerEm
    adv = {}
    for a, b in ranges:
        for cp in range(a, b + 1):
            g = cmap.get(cp)
            if g:
                adv[cp] = round(hmtx[g][0] * 1000 / upm)
    out["advances"][f["key"]] = adv

print(json.dumps(out))
`;

function runPython(cfg) {
  return JSON.parse(
    execFileSync('uv', ['run', '--no-project', '--with', 'fonttools==4.61.1', '--with', 'uharfbuzz==0.51.1', 'python', '-c', PY], {
      cwd: ROOT,
      input: JSON.stringify(cfg),
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
    }),
  );
}

const HEADER = (what) =>
  `// Generated by scripts/certificate-glyphs.mjs: ${what}\n// Do not edit by hand: change the script and run it again.\n`;

export function generate(root = ROOT) {
  const r = runPython({ signers: SIGNERS, faces: FACES });
  const sig = Object.fromEntries(
    Object.entries(r.signatures).map(([id, s]) => [id, { text: s.text, d: s.d, box: s.box }]),
  );
  const sources = SIGNERS.map((s) => `${s.id}: ${s.face.split('/').pop()}`).join('; ');
  writeFileSync(
    join(root, 'src/js/certificate/signatures.js'),
    HEADER(`the two signatures as path data at a font size of 100, baseline at y = 0 (box: ink bounds, x0 y0 x1 y1).\n// Converted from OFL script faces kept in scripts/signature-faces/ (${sources}); no script face ships.`) +
      `export const SIGNATURES = Object.freeze(${JSON.stringify(sig, null, 2)});\n`,
  );
  const adv = Object.fromEntries(Object.entries(r.advances).map(([k, v]) => [k, v]));
  writeFileSync(
    join(root, 'src/js/certificate/metrics.js'),
    HEADER('advance widths of the certificate faces in thousandths of an em, keyed by code point.') +
      `export const ADVANCES = Object.freeze(${JSON.stringify(adv)});\n`,
  );
  return ['src/js/certificate/signatures.js', 'src/js/certificate/metrics.js'];
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  console.log(`certificate glyphs: wrote ${generate().join(', ')}`);
}
